version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - node/install-yarn:
          version: 1.22.4
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            yarn run frontend:install
      - run:
          name: Back-End Install
          command: |
            yarn run backend:install
      - run:
          name: Front-End Build
          command: |
            yarn run frontend:build
      - run:
          name: Back-End Build
          command: |
            yarn run backend:build
      - run:
          name: front-End deploy app
          command: |
            yarn run frontend:deploy